[CmdletBinding()]
param(
    [string]$OutputRoot = "",
    [string]$RuntimeRoot = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$backendSource = Join-Path $repoRoot "esp-config-designer\backend"
$schemaCatalogSource = Join-Path $repoRoot "esp-config-designer\shared\schema-catalog"
$desktopPythonSource = Join-Path $repoRoot "desktop\python"
$frontendDist = Join-Path $repoRoot "esp-config-designer\frontend\dist"
$windowsPlatformSource = Join-Path $repoRoot "desktop\platforms\windows"

$defaultOutputRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\resources\ecd-app"))
$placeholderText = "Generated by scripts/package-resources.ps1. Development placeholder only."
if (-not $OutputRoot) {
    $OutputRoot = $defaultOutputRoot
}
if (-not $RuntimeRoot) {
    $RuntimeRoot = Join-Path $env:LOCALAPPDATA "ECD\runtime"
}

$OutputRoot = [System.IO.Path]::GetFullPath($OutputRoot)
$RuntimeRoot = [System.IO.Path]::GetFullPath($RuntimeRoot)
$backendOutput = Join-Path $OutputRoot "backend"
$schemaCatalogOutput = Join-Path $backendOutput "schema-catalog"
$runtimeOutput = Join-Path $OutputRoot "runtime"

foreach ($requiredPath in @(
    (Join-Path $backendSource "server.py"),
    (Join-Path $backendSource "runtime_contract.py"),
    (Join-Path $backendSource "runtime_manifest.py"),
    (Join-Path $backendSource "runtime_diagnostics.py"),
    (Join-Path $desktopPythonSource "desktop_launcher.py"),
    (Join-Path $desktopPythonSource "desktop_runtime.py"),
    (Join-Path $desktopPythonSource "application_payload.py"),
    (Join-Path $desktopPythonSource "runtime_update.py"),
    (Join-Path $backendSource "seed_esphome"),
    (Join-Path $schemaCatalogSource "components_list\components_list.json"),
    (Join-Path $schemaCatalogSource "schemas\components\custom\empty.json"),
    (Join-Path $frontendDist "index.html"),
    (Join-Path $windowsPlatformSource "git-manifest.json"),
    (Join-Path $RuntimeRoot "python.exe"),
    (Join-Path $RuntimeRoot "runtime-manifest.json"),
    (Join-Path $RuntimeRoot "git\LICENSE.txt")
)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Required packaging input is missing: $requiredPath"
    }
}

if (Test-Path -LiteralPath $OutputRoot) {
    $existingItems = @(Get-ChildItem -LiteralPath $OutputRoot -Force)
    $trackedMarker = Join-Path $OutputRoot "README.txt"
    $layoutMarker = Join-Path $OutputRoot "resource-layout.json"
    $isDefaultPlaceholder = (
        [string]::Equals($OutputRoot, $defaultOutputRoot, [System.StringComparison]::OrdinalIgnoreCase) -and
        $existingItems.Count -eq 1 -and
        $existingItems[0].Name -eq "README.txt" -and
        (Test-Path -LiteralPath $trackedMarker -PathType Leaf) -and
        (Get-Content -LiteralPath $trackedMarker -Raw).Trim() -eq $placeholderText
    )
    $isGeneratedOutput = $false
    if (Test-Path -LiteralPath $layoutMarker -PathType Leaf) {
        try {
            $existingLayout = Get-Content -LiteralPath $layoutMarker -Raw | ConvertFrom-Json
            $isGeneratedOutput = (
                $existingLayout.schemaVersion -eq 1 -and
                $existingLayout.kind -eq "ecd-tauri-resource-layout" -and
                $existingLayout.backend -eq "backend" -and
                $existingLayout.runtime -eq "runtime"
            )
        } catch {
            $isGeneratedOutput = $false
        }
    }
    if ($existingItems.Count -gt 0 -and -not $isGeneratedOutput -and -not $isDefaultPlaceholder) {
        throw "Refusing to clean a non-generated packaging output: $OutputRoot"
    }
    Get-ChildItem -LiteralPath $OutputRoot -Force |
        Where-Object { $_.Name -ne "README.txt" } |
        Remove-Item -Recurse -Force
}
New-Item -ItemType Directory -Path $backendOutput -Force | Out-Null
New-Item -ItemType Directory -Path $schemaCatalogOutput -Force | Out-Null
New-Item -ItemType Directory -Path $runtimeOutput -Force | Out-Null

foreach ($fileName in @("server.py", "runtime_contract.py", "runtime_manifest.py", "runtime_diagnostics.py")) {
    Copy-Item -LiteralPath (Join-Path $backendSource $fileName) -Destination (Join-Path $backendOutput $fileName)
}
foreach ($fileName in @("desktop_launcher.py", "desktop_runtime.py", "application_payload.py", "runtime_update.py")) {
    Copy-Item -LiteralPath (Join-Path $desktopPythonSource $fileName) -Destination (Join-Path $backendOutput $fileName)
}
Copy-Item -LiteralPath (Join-Path $backendSource "seed_esphome") -Destination $backendOutput -Recurse
Copy-Item -Path (Join-Path $schemaCatalogSource "*") -Destination $schemaCatalogOutput -Recurse -Force
$catalogContract = Join-Path $repoRoot "esp-config-designer\shared\schema-catalog-contract.mjs"
& node $catalogContract --root $schemaCatalogSource --write-manifest (Join-Path $backendOutput "schema-catalog-manifest.json")
if ($LASTEXITCODE -ne 0) {
    throw "Could not create the packaged schema catalog manifest"
}
New-Item -ItemType Directory -Path (Join-Path $backendOutput "web") -Force | Out-Null
Copy-Item -Path (Join-Path $frontendDist "*") -Destination (Join-Path $backendOutput "web") -Recurse -Force

Copy-Item -Path (Join-Path $RuntimeRoot "*") -Destination $runtimeOutput -Recurse -Force
Copy-Item -LiteralPath (Join-Path $windowsPlatformSource "git-manifest.json") -Destination (Join-Path $runtimeOutput "git-manifest.json")

foreach ($immutableRoot in @($backendOutput, $runtimeOutput)) {
    Get-ChildItem -LiteralPath $immutableRoot -Recurse -Force -Directory -Filter "__pycache__" |
        Sort-Object FullName -Descending |
        Remove-Item -Recurse -Force
    Get-ChildItem -LiteralPath $immutableRoot -Recurse -Force -File |
        Where-Object { $_.Extension -in @(".pyc", ".pyo") } |
        Remove-Item -Force
}

$layoutManifest = [ordered]@{
    schemaVersion = 1
    kind = "ecd-tauri-resource-layout"
    backend = "backend"
    webRoot = "backend/web"
    schemaCatalogRoot = "backend/schema-catalog"
    schemaCatalogManifest = "backend/schema-catalog-manifest.json"
    runtime = "runtime"
    mutableDataPolicy = "app-data-only"
    workspacePolicy = "user-selected-outside-app-data"
}
$layoutManifest | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $OutputRoot "resource-layout.json") -Encoding UTF8

Write-Host "[info] Packaged resources: $OutputRoot"
Write-Host "[info] Backend/web root: $(Join-Path $backendOutput 'web')"
Write-Host "[info] Embedded runtime: $runtimeOutput"
