[CmdletBinding()]
param(
    [string]$ResourcesRoot = ""
)

$ErrorActionPreference = "Stop"
if (-not $ResourcesRoot) {
    $ResourcesRoot = Join-Path $PSScriptRoot "..\resources\ecd-app"
}
$ResourcesRoot = [System.IO.Path]::GetFullPath($ResourcesRoot)
$backendRoot = Join-Path $ResourcesRoot "backend"
$runtimeRoot = Join-Path $ResourcesRoot "runtime"

foreach ($requiredPath in @(
    (Join-Path $ResourcesRoot "resource-layout.json"),
    (Join-Path $backendRoot "server.py"),
    (Join-Path $backendRoot "desktop_launcher.py"),
    (Join-Path $backendRoot "runtime_config.py"),
    (Join-Path $backendRoot "runtime_manifest.py"),
    (Join-Path $backendRoot "runtime_diagnostics.py"),
    (Join-Path $backendRoot "runtime_update.py"),
    (Join-Path $backendRoot "web\index.html"),
    (Join-Path $runtimeRoot "python.exe"),
    (Join-Path $runtimeRoot "runtime-manifest.json"),
    (Join-Path $runtimeRoot "git\cmd\git.exe"),
    (Join-Path $runtimeRoot "git\LICENSE.txt"),
    (Join-Path $runtimeRoot "git-manifest.json")
)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Packaged resource is missing: $requiredPath"
    }
}

if (Test-Path -LiteralPath (Join-Path $backendRoot "backend") -PathType Container) {
    throw "Packaged resources contain a nested backend source root"
}
if (Test-Path -LiteralPath (Join-Path $backendRoot "tests") -PathType Container) {
    throw "Backend tests must not be included in packaged resources"
}

$layout = Get-Content -LiteralPath (Join-Path $ResourcesRoot "resource-layout.json") -Raw | ConvertFrom-Json
if ($layout.mutableDataPolicy -ne "app-data-only") {
    throw "Resource layout allows mutable data outside app-data"
}
if ($layout.workspacePolicy -ne "user-selected-outside-app-data") {
    throw "Resource layout has an invalid workspace policy"
}

$catalogPath = Join-Path $backendRoot "web\components_list\components_list.json"
if (-not (Test-Path -LiteralPath $catalogPath -PathType Leaf)) {
    throw "Packaged component catalog is missing: $catalogPath"
}
$catalog = Get-Content -LiteralPath $catalogPath -Raw | ConvertFrom-Json
$catalogItems = @()
foreach ($category in @($catalog.categories)) {
    $catalogItems += @($category.items)
    foreach ($subcategory in @($category.subcategories)) {
        $catalogItems += @($subcategory.items)
    }
}
foreach ($item in $catalogItems) {
    if ($item.available -eq $false -or -not $item.schemaPath) { continue }
    $schemaPath = Join-Path (Join-Path $backendRoot "web\schemas") ($item.schemaPath -replace '/', '\')
    if (-not (Test-Path -LiteralPath $schemaPath -PathType Leaf)) {
        throw "Packaged component schema is missing: $($item.schemaPath)"
    }
}

$generatedFiles = Get-ChildItem -LiteralPath $ResourcesRoot -Recurse -Force -File |
    Where-Object { $_.Name -like "*.pyc" -or $_.Name -eq ".ecd-write-probe" -or $_.FullName -match "__pycache__" }
if ($generatedFiles) {
    throw "Generated bytecode or write probes are present in immutable resources"
}

Write-Host "[info] Packaged resource layout verified: $ResourcesRoot"
