[CmdletBinding()]
param(
    [string]$ResourcesRoot = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
if (-not $ResourcesRoot) {
    $ResourcesRoot = Join-Path $PSScriptRoot "..\resources\ecd-app"
}
$ResourcesRoot = [System.IO.Path]::GetFullPath($ResourcesRoot)
$backendRoot = Join-Path $ResourcesRoot "backend"
$schemaCatalogRoot = Join-Path $backendRoot "schema-catalog"
$webRoot = Join-Path $backendRoot "web"
$runtimeRoot = Join-Path $ResourcesRoot "runtime"
$supplyChainRoot = Join-Path $ResourcesRoot "supply-chain"

foreach ($requiredPath in @(
    (Join-Path $ResourcesRoot "resource-layout.json"),
    (Join-Path $backendRoot "server.py"),
    (Join-Path $backendRoot "desktop_launcher.py"),
    (Join-Path $backendRoot "desktop_runtime.py"),
    (Join-Path $backendRoot "application_payload.py"),
    (Join-Path $backendRoot "runtime_contract.py"),
    (Join-Path $backendRoot "runtime_manifest.py"),
    (Join-Path $backendRoot "runtime_diagnostics.py"),
    (Join-Path $backendRoot "runtime_update.py"),
    (Join-Path $backendRoot "web\index.html"),
    (Join-Path $schemaCatalogRoot "components_list\components_list.json"),
    (Join-Path $schemaCatalogRoot "schemas\components\custom\empty.json"),
    (Join-Path $backendRoot "schema-catalog-manifest.json"),
    (Join-Path $runtimeRoot "python.exe"),
    (Join-Path $runtimeRoot "runtime-manifest.json"),
    (Join-Path $runtimeRoot "git\cmd\git.exe"),
    (Join-Path $runtimeRoot "git\LICENSE.txt"),
    (Join-Path $runtimeRoot "git-manifest.json"),
    (Join-Path $runtimeRoot "python-manifest.json"),
    (Join-Path $runtimeRoot "requirements-bootstrap.lock"),
    (Join-Path $runtimeRoot "requirements-runtime.lock"),
    (Join-Path $supplyChainRoot "inventory.json"),
    (Join-Path $supplyChainRoot "THIRD-PARTY-NOTICES.md")
)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Packaged resource is missing: $requiredPath"
    }
}

$canonicalSupplyChainRoot = Join-Path $repoRoot "desktop\supply-chain"
foreach ($fileName in @("inventory.json", "THIRD-PARTY-NOTICES.md")) {
    $expectedHash = (Get-FileHash -LiteralPath (Join-Path $canonicalSupplyChainRoot $fileName) -Algorithm SHA256).Hash
    $actualHash = (Get-FileHash -LiteralPath (Join-Path $supplyChainRoot $fileName) -Algorithm SHA256).Hash
    if ($actualHash -ne $expectedHash) {
        throw "Packaged supply-chain metadata differs from the tracked source: $fileName"
    }
}

if (Test-Path -LiteralPath (Join-Path $backendRoot "backend") -PathType Container) {
    throw "Packaged resources contain a nested backend source root"
}
if (Test-Path -LiteralPath (Join-Path $backendRoot "tests") -PathType Container) {
    throw "Backend tests must not be included in packaged resources"
}
if (Test-Path -LiteralPath (Join-Path $backendRoot "runtime_config.py") -PathType Leaf) {
    throw "Packaged resources contain the obsolete mixed runtime_config.py"
}
if (Test-Path -LiteralPath (Join-Path $schemaCatalogRoot "schema-catalog") -PathType Container) {
    throw "Packaged resources contain a nested schema-catalog root"
}

$layout = Get-Content -LiteralPath (Join-Path $ResourcesRoot "resource-layout.json") -Raw | ConvertFrom-Json
if ($layout.mutableDataPolicy -ne "app-data-only") {
    throw "Resource layout allows mutable data outside app-data"
}
if ($layout.workspacePolicy -ne "user-selected-outside-app-data") {
    throw "Resource layout has an invalid workspace policy"
}
if ($layout.schemaCatalogRoot -ne "backend/schema-catalog") {
    throw "Resource layout has an invalid schema catalog root"
}
if ($layout.schemaCatalogManifest -ne "backend/schema-catalog-manifest.json") {
    throw "Resource layout has an invalid schema catalog manifest"
}

$catalogContract = Join-Path $repoRoot "esp-config-designer\shared\schema-catalog-contract.mjs"
$canonicalCatalog = Join-Path $repoRoot "esp-config-designer\shared\schema-catalog"
& node $catalogContract --root $canonicalCatalog --projection $schemaCatalogRoot
if ($LASTEXITCODE -ne 0) {
    throw "Packaged schema catalog differs from the canonical source"
}
& node $catalogContract --root $schemaCatalogRoot --manifest (Join-Path $backendRoot "schema-catalog-manifest.json")
if ($LASTEXITCODE -ne 0) {
    throw "Packaged schema catalog manifest is invalid"
}
& node $catalogContract --root $schemaCatalogRoot --projection $webRoot
if ($LASTEXITCODE -ne 0) {
    throw "Frontend web catalog differs from the packaged backend catalog"
}

$generatedFiles = Get-ChildItem -LiteralPath $ResourcesRoot -Recurse -Force -File |
    Where-Object { $_.Name -like "*.pyc" -or $_.Name -eq ".ecd-write-probe" -or $_.FullName -match "__pycache__" }
if ($generatedFiles) {
    throw "Generated bytecode or write probes are present in immutable resources"
}

Write-Host "[info] Packaged resource layout verified: $ResourcesRoot"
