[CmdletBinding()]
param(
    [string]$ResourcesRoot = ""
)

$ErrorActionPreference = "Stop"
if (-not $ResourcesRoot) {
    $ResourcesRoot = Join-Path $PSScriptRoot "..\resources\ecd-app"
}
$ResourcesRoot = [System.IO.Path]::GetFullPath($ResourcesRoot)
$backendRoot = Join-Path $ResourcesRoot "backend"
$runtimeRoot = Join-Path $ResourcesRoot "runtime"

foreach ($requiredPath in @(
    (Join-Path $ResourcesRoot "resource-layout.json"),
    (Join-Path $backendRoot "server.py"),
    (Join-Path $backendRoot "desktop_launcher.py"),
    (Join-Path $backendRoot "runtime_config.py"),
    (Join-Path $backendRoot "runtime_manifest.py"),
    (Join-Path $backendRoot "runtime_update.py"),
    (Join-Path $backendRoot "web\index.html"),
    (Join-Path $runtimeRoot "python.exe"),
    (Join-Path $runtimeRoot "runtime-manifest.json"),
    (Join-Path $runtimeRoot "git\cmd\git.exe"),
    (Join-Path $runtimeRoot "git\LICENSE.txt"),
    (Join-Path $runtimeRoot "git-manifest.json")
)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        throw "Packaged resource is missing: $requiredPath"
    }
}

$layout = Get-Content -LiteralPath (Join-Path $ResourcesRoot "resource-layout.json") -Raw | ConvertFrom-Json
if ($layout.mutableDataPolicy -ne "app-data-only") {
    throw "Resource layout allows mutable data outside app-data"
}
if ($layout.workspacePolicy -ne "user-selected-outside-app-data") {
    throw "Resource layout has an invalid workspace policy"
}

$generatedFiles = Get-ChildItem -LiteralPath $ResourcesRoot -Recurse -Force -File |
    Where-Object { $_.Name -like "*.pyc" -or $_.Name -eq ".ecd-write-probe" -or $_.FullName -match "__pycache__" }
if ($generatedFiles) {
    throw "Generated bytecode or write probes are present in immutable resources"
}

Write-Host "[info] Packaged resource layout verified: $ResourcesRoot"
