services:
  esp-config-designer:
    labels:
      com.centurylinklabs.watchtower.scope: ecd

  watchtower:
    image: containrrr/watchtower:latest
    container_name: ecd-watchtower
    restart: unless-stopped
    command: --scope ecd --cleanup --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.scope: ecd
